project:
  type: website
  output-dir: docs
website:
  title: "rblogr"
  navbar:
    right:
      - projects.qmd
      - about.qmd
      
      - icon: github
        href: https://github.com/bradfordjohnson
format:
  html:
    theme: sandstone
    css: styles.css

editor: visual

